#!/bin/sh
#other issues:
#  If swapfile could not be installed at boot try https://www.digitalocean.com/community/articles/how-to-add-swap-on-ubuntu-12-04
sudo apt-get install chromium-browser
sudo apt-get install mercurial
#-----
sudo apt-get install python-pip
sudo pip install selenium
#-----
apt-get install libxml2-dev libxslt1-dev python-dev
apt-get install python-lxml
#-----
sudo apt-get install git
#-----
sudo add-apt-repository "deb http://archive.canonical.com/ $(lsb_release -sc) partner"
sudo apt-get install skype
#-----
sudo apt-get install vinagre
#-----
sudo add-apt-repository ppa:michael-astrapi/ppa
sudo apt-get update && sudo apt-get install truecrypt
#-----
sudo apt-get install exuberant-ctags
sudo apt-get install debsums
sudo apt-get install vim-gnome
