#!/bin/sh
#other issues:
#  If swapfile could not be installed at boot try https://www.digitalocean.com/community/articles/how-to-add-swap-on-ubuntu-12-04

sudo apt-get install git
sudo apt-get install vinagre
sudo add-apt-repository ppa:michael-astrapi/ppa
sudo apt-get update && sudo apt-get install truecrypt
sudo apt-get install exuberant-ctags
sudo apt-get install exuberant-ctags
sudo apt-get install debsums
sudo apt-get install vim-gnome
