#!/bin/sh

# link dotfiles into home directory

cd
rm -rf ~/.vim ~/.vimrc ~/.vimperatorrc ~/.gvimrc ~/.bashrc 
rm -rf ~/binScripts
rm -rf ~/.inputrc
for f in .dotfiles/* .dotfiles/.??*
do
	test "$f" != ".dotfiles/.git" -a "$f" != ".dotfiles/README.md" && ln -sf $f .
done

git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
